server:
  port: 56040

spring:
  application:
    name: dubbo-service1
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    base-packages: com.eimya.microservice.service1.service
  protocol:
    # dubbo协议
    name: dubbo
    # dubbo协议端口
    port: 20891
  registry:
    address: nacos://127.0.0.1:8848
  application:
    # dubbo运维服务是否开启
    qos-enable: false
  consumer:
    # dubbo启动时是否检查依赖的服务
    check: false