server:
  port: 56030

spring:
  application:
    name: dubbo-service2
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 88925201-ed58-4af9-934a-cb8569c3f3ed
dubbo:
  scan:
    base-packages: com.eimya.microservice.service2.service
  protocol:
    # dubbo协议
    name: dubbo
    # dubbo协议端口
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848
  application:
    # dubbo运维服务是否开启
    qos-enable: false
  consumer:
    # dubbo启动时是否检查依赖的服务
    check: false